--
-- Name: academic_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.academic_history (
                                         specialist_id uuid NOT NULL,
                                         academic_history character varying(255)
);


ALTER TABLE public.academic_history OWNER TO postgres;

--
-- Name: availabilities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.availabilities (
                                       end_time time(6) without time zone NOT NULL,
                                       start_time time(6) without time zone NOT NULL,
                                       id bigint NOT NULL,
                                       specialist_id uuid NOT NULL,
                                       uuid uuid NOT NULL,
                                       day_of_week character varying(255) NOT NULL,
                                       CONSTRAINT availabilities_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


ALTER TABLE public.availabilities OWNER TO postgres;

--
-- Name: availabilities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.availabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.availabilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client_profiles (
                                        date_of_birth timestamp(6) without time zone,
                                        user_id uuid NOT NULL,
                                        external_customer_id character varying(255),
                                        name character varying(255),
                                        phone_number character varying(255),
                                        relationship_degree character varying(255),
                                        CONSTRAINT client_profiles_relationship_degree_check CHECK (((relationship_degree)::text = ANY ((ARRAY['CONJUGE'::character varying, 'FILHO'::character varying, 'IRMAO'::character varying, 'MAE'::character varying, 'NETO'::character varying, 'PAI'::character varying, 'SOBRINHO'::character varying, 'TIO'::character varying, 'AMIGO'::character varying, 'CUNHADO'::character varying, 'GENRO'::character varying, 'NORA'::character varying, 'SOGRO'::character varying, 'AVO'::character varying, 'COMPANHEIRO'::character varying, 'OUTRO'::character varying])::text[])))
);


ALTER TABLE public.client_profiles OWNER TO postgres;

--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
                                              used boolean NOT NULL,
                                              expires_at timestamp(6) with time zone,
                                              used_at timestamp(6) with time zone,
                                              id uuid NOT NULL,
                                              user_id uuid,
                                              token character varying(255)
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- Name: payment_split_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_split_rules (
                                            active boolean NOT NULL,
                                            percentage numeric(5,2) NOT NULL,
                                            created_at timestamp(6) without time zone,
                                            id uuid NOT NULL,
                                            specialist_id uuid NOT NULL,
                                            scope character varying(255) NOT NULL,
                                            specialist_type character varying(255),
                                            CONSTRAINT payment_split_rules_scope_check CHECK (((scope)::text = ANY ((ARRAY['SPECIALIST'::character varying, 'SPECIALIST_TYPE'::character varying, 'GLOBAL'::character varying])::text[]))),
    CONSTRAINT payment_split_rules_specialist_type_check CHECK (((specialist_type)::text = ANY ((ARRAY['PSICOLOGO'::character varying, 'PSIQUIATRA'::character varying, 'TERAPEUTA'::character varying, 'EDUCADOR_FISICO'::character varying, 'NUTRICIONISTA'::character varying, 'ASSESSOR_FINANCEIRO'::character varying])::text[])))
);


ALTER TABLE public.payment_split_rules OWNER TO postgres;

--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
                                 amount numeric(10,2),
                                 discount_amount numeric(10,2),
                                 final_amount numeric(10,2),
                                 original_amount numeric(10,2),
                                 platform_amount numeric(10,2),
                                 specialist_amount numeric(10,2),
                                 created_at timestamp(6) without time zone,
                                 paid_at timestamp(6) without time zone,
                                 refunded_at timestamp(6) without time zone,
                                 updated_at timestamp(6) without time zone,
                                 client_id uuid NOT NULL,
                                 id uuid NOT NULL,
                                 session_id uuid NOT NULL,
                                 specialist_id uuid NOT NULL,
                                 external_payment_id character varying(255),
                                 payment_method character varying(255) NOT NULL,
                                 payment_status character varying(255) NOT NULL,
                                 CONSTRAINT payments_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CREDIT_CARD'::character varying, 'BOLETO'::character varying, 'PIX'::character varying, 'DEBIT_CARD'::character varying])::text[]))),
    CONSTRAINT payments_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['CREATED'::character varying, 'PENDING'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
                                 end_at timestamp(6) without time zone NOT NULL,
                                 start_at timestamp(6) without time zone NOT NULL,
                                 client_id uuid NOT NULL,
                                 session_id uuid NOT NULL,
                                 specialist_id uuid NOT NULL,
                                 status character varying(255) NOT NULL,
                                 CONSTRAINT sessions_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULING'::character varying, 'AWAITING_PAYMENT'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: specialist_payout_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specialist_payout_accounts (
                                                   status boolean NOT NULL,
                                                   created_at timestamp(6) without time zone,
                                                   id uuid NOT NULL,
                                                   specialist_id uuid NOT NULL,
                                                   external_account_id character varying(255) NOT NULL,
                                                   provider character varying(255),
                                                   CONSTRAINT specialist_payout_accounts_provider_check CHECK (((provider)::text = 'ASAAS'::text))
);


ALTER TABLE public.specialist_payout_accounts OWNER TO postgres;

--
-- Name: specialist_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specialist_profiles (
                                            amount numeric(10,2),
                                            user_id uuid NOT NULL,
                                            about character varying(255),
                                            external_payout_account_id character varying(255),
                                            personal_description character varying(255),
                                            presentation_video_url character varying(255),
                                            registration_number character varying(255),
                                            specialist_type character varying(255),
                                            base64image text,
                                            CONSTRAINT specialist_profiles_specialist_type_check CHECK (((specialist_type)::text = ANY ((ARRAY['PSICOLOGO'::character varying, 'PSIQUIATRA'::character varying, 'TERAPEUTA'::character varying, 'EDUCADOR_FISICO'::character varying, 'NUTRICIONISTA'::character varying, 'ASSESSOR_FINANCEIRO'::character varying])::text[])))
);


ALTER TABLE public.specialist_profiles OWNER TO postgres;

--
-- Name: specializations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specializations (
                                        specialist_id uuid NOT NULL,
                                        specialization character varying(255)
);


ALTER TABLE public.specializations OWNER TO postgres;

--
-- Name: therapeutic_approaches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.therapeutic_approaches (
                                               specialist_id uuid NOT NULL,
                                               therapeutic_approach character varying(255)
);


ALTER TABLE public.therapeutic_approaches OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              user_id uuid NOT NULL,
                              city character varying(255),
                              cpf character varying(255) NOT NULL,
                              email character varying(255) NOT NULL,
                              name character varying(255) NOT NULL,
                              neighbourhood character varying(255),
                              password character varying(255) NOT NULL,
                              role character varying(255) NOT NULL,
                              state character varying(255),
                              status character varying(255) NOT NULL,
                              street character varying(255),
                              telephone character varying(255) NOT NULL,
                              zip_code character varying(255),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT'::character varying, 'SPECIALIST'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: webhook_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.webhook_events (
                                       received_at timestamp(6) with time zone NOT NULL,
                                       id uuid NOT NULL,
                                       event_type character varying(255),
                                       external_event_id character varying(255) NOT NULL,
                                       external_payment_id character varying(255) NOT NULL,
                                       CONSTRAINT webhook_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['PAID'::character varying, 'OVERDUE'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'IGNORE'::character varying])::text[])))
);


ALTER TABLE public.webhook_events OWNER TO postgres;

--
-- Name: availabilities availabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.availabilities
    ADD CONSTRAINT availabilities_pkey PRIMARY KEY (id);


--
-- Name: availabilities availabilities_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.availabilities
    ADD CONSTRAINT availabilities_uuid_key UNIQUE (uuid);


--
-- Name: client_profiles client_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client_profiles
    ADD CONSTRAINT client_profiles_pkey PRIMARY KEY (user_id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: payment_split_rules payment_split_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_split_rules
    ADD CONSTRAINT payment_split_rules_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (session_id);


--
-- Name: specialist_payout_accounts specialist_payout_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialist_payout_accounts
    ADD CONSTRAINT specialist_payout_accounts_pkey PRIMARY KEY (id);


--
-- Name: specialist_profiles specialist_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialist_profiles
    ADD CONSTRAINT specialist_profiles_pkey PRIMARY KEY (user_id);


--
-- Name: users users_cpf_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_cpf_key UNIQUE (cpf);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: webhook_events webhook_events_external_event_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.webhook_events
    ADD CONSTRAINT webhook_events_external_event_id_key UNIQUE (external_event_id);


--
-- Name: webhook_events webhook_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.webhook_events
    ADD CONSTRAINT webhook_events_pkey PRIMARY KEY (id);


--
-- Name: specializations fk5vd7r5os6h2v19g25llfaxa3m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specializations
    ADD CONSTRAINT fk5vd7r5os6h2v19g25llfaxa3m FOREIGN KEY (specialist_id) REFERENCES public.specialist_profiles(user_id);


--
-- Name: academic_history fk9404vip5mqdxyyjlkbs84mawi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.academic_history
    ADD CONSTRAINT fk9404vip5mqdxyyjlkbs84mawi FOREIGN KEY (specialist_id) REFERENCES public.specialist_profiles(user_id);


--
-- Name: therapeutic_approaches fkovqcxg2wrscnafk3cms66qqcj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.therapeutic_approaches
    ADD CONSTRAINT fkovqcxg2wrscnafk3cms66qqcj FOREIGN KEY (specialist_id) REFERENCES public.specialist_profiles(user_id);